# Generated by Django 4.1.4 on 2022-12-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_rename_upload_uploads_link_uploads_date_of_issue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploads",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="client.client"
            ),
        ),
    ]
