# Generated by Django 4.1.4 on 2022-12-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_remove_schedule_start_schedule_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="doc",
        ),
        migrations.AddField(
            model_name="schedule",
            name="doc",
            field=models.ManyToManyField(to="doctor.doctor"),
        ),
    ]
