# Generated by Django 4.1.4 on 2022-12-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_remove_schedule_doc_schedule_doc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="doc",
        ),
        migrations.AddField(
            model_name="schedule",
            name="doc",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.doctor",
            ),
            preserve_default=False,
        ),
    ]
