# Generated by Django 4.1.4 on 2022-12-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_remove_schedule_doc_schedule_doc"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Time",
        ),
    ]
