# Generated by Django 4.1.4 on 2022-12-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_delete_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="no_of_hours",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
