# Generated by Django 4.1.4 on 2022-12-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_schedule_no_of_hours_alter_schedule_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="doc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
            ),
        ),
    ]
