# Generated by Django 4.1.4 on 2022-12-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_alter_schedule_doc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="no_of_hours",
        ),
        migrations.AddField(
            model_name="schedule",
            name="taken",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
