# Generated by Django 4.1.4 on 2022-12-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_remove_schedule_no_of_hours_schedule_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="taken",
            field=models.BooleanField(default=False),
        ),
    ]
