# Generated by Django 4.1.4 on 2022-12-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0009_alter_schedule_taken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="name",
        ),
    ]
