# Generated by Django 4.1.4 on 2022-12-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_remove_client_name"),
        ("doctor", "0010_remove_doctor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="taken",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="client.client"
            ),
        ),
    ]
