# Generated by Django 4.1.4 on 2022-12-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0012_alter_schedule_taken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specializations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spec", models.CharField(max_length=200)),
            ],
        ),
    ]
