# Generated by Django 4.1.4 on 2022-12-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0015_alter_doctor_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
