# Generated by Django 4.1.4 on 2022-12-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0016_schedule_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
