# Generated by Django 4.1.4 on 2022-12-24 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_remove_client_name"),
        ("doctor", "0017_schedule_cancelled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="cancelled",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cancelled",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="taken",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taken",
                to="client.client",
            ),
        ),
    ]
